
WHITELIST = ['aa',
             'aj',
             'Christina',
             'cpu',
             'daim',
             'ea',
             'ianp',
             'jobrandh',
             'joe_and',
             'ladt',
             'littlerob',
             'mapeppa',
             'ob',
             'pledeser',
             #'rwge',
             'shamayl',
             'srj',
             'tjw',
             'uu',
             'vidubois',]

BUZZPLAYERS = [ 'aa',
                'aj',
                'Christina',
                'ea',
                'ianp',
                'jobrandh',
                'joe_and',
                'littlerob',
                'mapeppa',
                'ob',
                'pledeser',
                #'rwge',
                'srj',
                'tjw',
                'uu',
                'vidubois',
                ]